name: project
recipe: drupal9
config:
  webroot: docroot
  php: "8.1"

  # For projects on the OVH server, MYSQL 8 is required to sync databases.
  # See https://github.com/lando/lando/issues/2948#issuecomment-1003484299
  database: mysql:8.0.22
  config:
    database: /dev/null
